### ISSUE TITLE
how to invoke this???

### ISSUE THREAD

**Issue by unixbhaskar** [mdnghtman/mpv-i3-floating-centered#1]
Your Readme page elaborate more. Give example to invoke and how.

Putting the scripts on .config/mpv/scripts  not do the job....tell us how exactly it can use...

**Comment by mdnghtman** [comment]
Hello unixbhaskar.

Let's see. I guess you're right about this. I'll change the readme.
I was missing to say that in order for this script to work, you got to have _**xdotool**_ and _**xorg-xprop**_ installed.

If you like, please report back. Thanks for the thoughtful criticism.
