### ISSUE TITLE
I don't need external script to get this 

### ISSUE THREAD

**Issue by c02y** [mdnghtman/mpv-i3-floating-centered#3]
```
for_window [class="mpv"] floating enable, resize set 70 ppt 80 ppt, move position center
```

**Comment by mdnghtman** [comment]
You'll need it if you're going to play a playlist of files with different resolutions.

**Comment by c02y** [comment]
Then I remove "resize set 70 ppt 80 ppt"?

Another thing out of topic:
`floating_maximum_size 1920 x 1080` is in my config, 

When I use `window-scale` binding to resize my video, it is totally wrong, when I play `1920x1080` video, from the beginning when you open the video,  `window-scale = 0.5` will resize the video a little bigger than  (which should 50%  of) the size when you open it,  then `window-scale = 1` binding will make the size (which should be `1920x1080`) of the video much bigger than my `2560x1440` screen.

Sorry to bother you here, I just started to use i3 for a few days and found nothing like this from googling or mpv github repo.


----------------------
**UPDATE**:

Fix it with `no-hidpi-window-scale` in mpv.conf
